# Generated by Django 3.0.8 on 2020-07-26 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_shot'),
    ]

    operations = [
        migrations.AddField(
            model_name='shot',
            name='in_out',
            field=models.CharField(choices=[('in', 'in'), ('out', 'out'), ('net', 'net')], default='in', max_length=100),
        ),
        migrations.AddField(
            model_name='shot',
            name='landing_spot',
            field=models.CharField(choices=[('deep cross', 'deep cross'), ('deep line', 'deep line'), ('short cross', 'short cross'), ('short line', 'short line')], default='deep cross', max_length=100),
        ),
        migrations.AddField(
            model_name='shot',
            name='shot_location',
            field=models.CharField(choices=[('deep left', 'deep left'), ('deep right', 'deep right'), ('short left', 'short left'), ('short right', 'short right')], default='deep left', max_length=100),
        ),
        migrations.AddField(
            model_name='shot',
            name='shot_type',
            field=models.CharField(choices=[('forehand', 'forehand'), ('backhand', 'backhand'), ('volley', 'volley')], default='forehand', max_length=100),
        ),
    ]
