# Generated by Django 3.0.8 on 2020-07-27 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_auto_20200726_1609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shot',
            name='in_out',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='shot',
            name='landing_spot',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='shot',
            name='shot_location',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='shot',
            name='shot_type',
            field=models.CharField(max_length=100),
        ),
    ]
