# Generated by Django 3.0.8 on 2020-07-27 20:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_auto_20200727_0254'),
    ]

    operations = [
        migrations.AddField(
            model_name='shot',
            name='pub_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date published'),
        ),
        migrations.AddField(
            model_name='shot',
            name='shot_group',
            field=models.CharField(default='1', max_length=20),
        ),
    ]
